### ISSUE TITLE
[Feature Request] 自动识别恶意弹幕

### ISSUE THREAD

**Issue by forest0** [jarheadjoe/DanmuPunish#2]
搜了下github上还是有不少关于弹幕的仓库，
想了想，一个可能有不少用户想要的功能是：
能不能自动地识别恶意弹幕并屏蔽之？

**Comment by jarheadjoe** [comment]
不可以，没有bilibili接口

**Comment by forest0** [comment]
在web上是肯定可以拿到弹幕列表的，过滤应该也好实现，难点在于识别

**Comment by jarheadjoe** [comment]
暂时没有看到识别的必要性

**Comment by jarheadjoe** [comment]
弹幕列表功能都已经实现，可以试一下

**Comment by forest0** [comment]
> 暂时没有看到识别的必要性

我想的是做在浏览器上，自动屏蔽了

**Comment by jarheadjoe** [comment]
你的想法那和我项目的初衷不太一样。屏蔽功能bilibili有弹幕管理。再做插件兼容难度大，意义觉得不是很大
